radicle-dev/infra

linux/etc/buildkite-agent/hooks/environment

Bump cache volume quota

---

README.md

Document caching in README

---

README.md
linux/bootstrap.sh
linux/etc/apt/sources.list.d/sops.list
linux/etc/buildkite-agent/hooks/pre-command

Sops user secrets

---

README.md
linux/etc/buildkite-agent/hooks/command
linux/etc/buildkite-agent/hooks/environment

We change the image building functionality. Now it is possible to build a docker image that includes artifacts generated by a job. See the updated README for documentation.

Improved docker image building

---

linux/etc/buildkite-agent/hooks/command
linux/etc/buildkite-agent/hooks/environment

I _believe_ this is logically correct, from looking at a few different build's "Environment" tab.

Fix check for "trusted" upstreams, once more

---

README.md
linux/etc/buildkite-agent/hooks/environment

Add support for shared master cache. See README for details.
Fixes #29

Add support for shared master cache

---

README.md
macos/usr/local/etc/buildkite-agent/buildkite-agent.cfg
macos/usr/local/etc/buildkite-agent/hooks/environment

Related to: https://github.com/radicle-dev/radicle-upstream/pull/94

Document macOS build agent setup

---

README.md
linux/etc/buildkite-agent/hooks/command
linux/etc/buildkite-agent/hooks/environment

I would like to use `buildkite-agent annotate` from builds.

Mount buildkite agent into build container

---

linux/etc/buildkite-agent/hooks/command
linux/etc/buildkite-agent/hooks/environment

See https://github.com/oscoin/zockervols/pull/12

Use refquota instead of quota for cache volumes

---

linux/etc/buildkite-agent/hooks/command

Let me know if this looks right

Create a branch cache volume for untrusted builds

---

linux/etc/buildkite-agent/hooks/command

After this PR, the bash code shall be frozen, and all further development shallt take place in #54

Fix some bash woes from #58

---

registry/.gitignore
registry/README.md
registry/backend.tf
registry/ci-secrets.tf
registry/devnet-miners.tf
registry/devnet-run-validator.sh
registry/devnet-telemetry.tf
registry/devnet-updater.tf
registry/devnet-validators.tf
registry/images/telemetry-backend/Dockerfile
registry/images/telemetry-backend/build.sh
registry/images/telemetry-frontend/Dockerfile
registry/images/telemetry-frontend/build.sh
registry/images/telemetry-frontend/feed-address.patch
registry/main.tf
registry/monitoring.tf
registry/prometheus.yaml

Import the current radicle registry infrastructure. Closes #68.
I’d prefer to make as little changes to the code as possible since this is just transferring code. Any concerns can be addressed by creating issues.

Import registry infrastructure

---

registry/devnet/run-validator.sh

See https://github.com/radicle-dev/radicle-registry/pull/357

Remove --name option from node arguments

---

registry/README.md
registry/devnet/main.tf
registry/devnet/miners.tf
registry/devnet/validators.tf

We document how to reset the devnet chain.

registry: Add runbook for resetting the devnet chain

---

registry/ffnet/README.md
registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

Adds documentation for the initial alerts introduced for https://github.com/radicle-dev/infra/issues/88

Add grafana dashboard JSON

---

registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

Fixes https://github.com/radicle-dev/infra/issues/96 and temporarily improves situation with https://github.com/radicle-dev/infra/issues/95.

Reduce number of Grafana false alarms

---

registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

Fixes https://github.com/radicle-dev/infra/issues/96, once again.

Increase mining alert from 7 to 11 minutes

---

registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

Fixes https://github.com/radicle-dev/infra/issues/92 and https://github.com/radicle-dev/infra/issues/93

Add high block rate and connections alert

---

.buildkite/build-buildkite-hooks.sh
.buildkite/pipeline.yaml

Fix some paths for uploading artifacts

Artifact fixes

---

ci/src/bin/buildkite-command-hook.rs
ci/src/cmd.rs
ci/src/container/docker.rs

A couple of minor fixes. See the commits for details.

Rusty hooks: minor fixes

---

ci/src/bin/buildkite-command-hook.rs
ci/src/bin/buildkite-pre-checkout-hook.rs
ci/src/cmd.rs
ci/src/container/docker.rs
ci/src/container/mod.rs

Another set of small fixes for rusty hooks. See the commit descriptions for details.

Small fixes for rusty hooks

---

registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

Fixes https://github.com/radicle-dev/infra/issues/93

Restrict grafana block import rate alerts to validators

---

registry/devnet/updater.tf

Fixes failing automatic deployment of devnet miner nodes

Fix devnet miner deployment privileges

---

registry/ffnet/miners.tf

We require mining pods to be scheduled on mining nodes. Mining on the n2 instances of the regular nodes is inefficient compared to the c2 instances of mining node pool.

Run miners only on mining nodes

---

.buildkite/build-buildkite-hooks.sh
.buildkite/common.sh
.buildkite/package-zockervols.sh
.buildkite/pipeline.yaml
registry/main.tf

A couple of improvements for how the project is build. See commits for details.

Build improvements

---

Cargo.lock
ci/Cargo.toml
ci/src/bin/buildkite-command-hook.rs
ci/src/config.rs
ci/src/container/mod.rs

Tag step images with vcs tag

---

registry/ffnet/miners.tf

Scale down ffnet miners

---

ci/README.md
registry/README.md

Documents GCS for https://github.com/radicle-dev/radicle-registry/issues/492

Add docs for registry runtimes GCS
