etc/buildkite-agent/hooks/command
etc/buildkite-agent/hooks/environment

i.e. the `timeout_in_minutes` step attribute

Allow user-specified timeouts for "trusted" builds

---

README.md
linux/etc/buildkite-agent/hooks/command
linux/etc/buildkite-agent/hooks/environment

* bash OCD
* indentation
* use function arguments instead of global variables)
* Rename the variables to trigger a "step docker build"
* Instead of a boolean and a conventional "image context" directory, let
users specify the image context.
* Allow to push to any registry
* Fix the check for 3rd party PRs

Edits to #20

---

linux/etc/buildkite-agent/hooks/command

* We create a new output log folding group for the docker image build. This prevents the output being displayed in the previous group defined by the CI script.
* We pull the image builder image quietly.

Improved log output when building image

---

linux/etc/buildkite-agent/hooks/command

Otherwise, due to `set -e`, the script will exit with an error.

Properly guard against STEP_DOCKER_FILE / STEP_DOCKER_IMAGE not being bound.

---

linux/etc/systemd/system/docker-volume-prune.sh

shellcheck did recommend read at some point, but that doesn't seem to do
the right thing.
Fixes #30

Use mapfile instead of read -ra when evaluating prunable cache volumes.

---

README.md
linux/etc/buildkite-agent/hooks/environment

Huge face-palm: Swapped the branches in the `if` statement. I already deployed the changes to not break any builds.

Fix shared master cache

---

README.md
linux/etc/buildkite-agent/hooks/environment
linux/etc/buildkite-agent/hooks/post-checkout

* Per repo secrets are only available for trusted builds
* Fix a couple of things that did not work

Secrets only for trusted builds

---

linux/etc/buildkite-agent/hooks/environment

We set the `volume-nocopy` option for cache mounts. This prevents docker from copying the content of `/cache` that is already present in the image to cache volume. This behavior caused issues when `/cache` in the image was owned by root which then changed the permissions of the cache volume mountpoint.

Use volume-nocopy for cache mount

---

README.md
linux/etc/buildkite-agent/hooks/environment
linux/etc/systemd/system/buildkite-agent@.service.d/local.conf

This provides a convenient way to publish build artifacts which do not require a package index (such as .deb packages).
_**Note**: the certificate DNS entry doesn't seem to be propagated yet, which also prevents TLS certificate provisioning. Use `https://storage.googleapis.com/builds.radicle.xyz` in the meantime.`_

Store build artifacts in our own GCS bucket

---

linux/bootstrap.sh

on the `tank/zocker` dataset
cf. #49, oscoin/zockervols#12

Allow the `buildkite-builder` to set the `refquota` property

---

linux/etc/buildkite-agent/hooks/command

We inject the `BUILDKITE_AGENT_ACCESS_TOKEN` into build containers instead of the `BUILDKITE_AGENT_TOKEN` to make `buildkite-agent` work. The latter is used to connect a running agent while the former is appropriate for interacting with a build.
See https://buildkite.com/docs/agent/v3/tokens#session-tokens

Inject proper agent token via env

---

linux/bootstrap.sh
linux/etc/buildkite-agent/hooks/command

When creating an anonymous volume for untrusted builds, we can't
manually adjust the permissions on the `/cache` mountpoint. Since the
stock `img` docker image runs under the hardcoded uid 1000, it can't
write there. We can remedy this by using a custom docker image with the
same uid as `buildkite-builder`.

Match `img` user uid with `buildkite-builder`

---

linux/etc/buildkite-agent/hooks/command

* Something with the embedded runc hack of `img` doesn't work -- use a
custom image which copies runc into the image, and disable img looking
for an embedded one
* Specify all volume options of the parent when creating an anonymous
snapshot. Otherwise, zockervols will reset the to undesirable
defaults.

Fix unprivileged builds unable to build docker images

---

linux/bootstrap.sh
linux/etc/buildkite-agent/hooks/command

kata-containers segfault when sharing executables with the host OS.
This is particularly annoying with --init: if a runc container is using
tini (/usr/bin/docker-init) currently, no kata-containers container can
run. Curiously, sharing a copy of tini amongst ONLY kata-containers
seems to work.
See: https://github.com/kata-containers/runtime/issues/1901

Work around kata-containers shared executables bug

---

registry/README.md
registry/monitoring.tf
registry/prometheus.yaml
registry/secrets.yaml

_Based on #74. Only the last commit is relevant_
We start sending our metrics to Grafana Cloud by adding a `remote_write` section to our Prometheus configuration.

Connect Prometheus to Grafana Cloud

---

registry/prometheus.yaml

To better distinguish metrics from different clusters we label them with the cluster name.

Add kubernetes_cluster label for metrics

---

registry/README.md
registry/dns.tf
registry/ffnet/README.md
registry/ffnet/boot.tf
registry/ffnet/validators.tf
registry/main.tf

We add DNS entries `boot-X.ff.radicle.network` that point to two validators of the FFnet. Run `terraform output` to get the addresses to pass to a node.

Domain names for boot nodes

---

registry/ffnet/main.tf
registry/ffnet/rpc-api.tf
registry/main.tf

We setup a load balancer service for the node RPC API for the devnet. The load balancer has the domain `rpc.ff.radicle.network`.
We also increase the machine size of the default pool to two cores. Otherwise it is impossible to schedule more than two validators on one K8s node. We prefer this approach to increasing the number of VMs because each VMs comes with an overhead (logging, metrics, proxy services).

registry: Set up node RPC service for FFnet

---

registry/devnet/miners.tf

We add the “app” label to the devnet miner deployment. Kubernetes does this automatically even if it is not specified in terraform. So when to avoid unnecessary diffs we add it to terraform.

registry: Add labels to devnet miner deployment

---

registry/ffnet/main.tf

We update the node version that is deployed on the ffnet. This includes https://github.com/radicle-dev/radicle-registry/pull/373 and requires a restart of the network.

registry: Update ffnet node version

---

ci/README.md
ci/linux/etc/buildkite-agent/hooks/command
ci/linux/etc/buildkite-agent/hooks/environment

Fixes #89
Binary artifacts and docker images are identified by `BUILDKITE_TAG` for tag builds. Since the usage of `BUILDKITE_TAG` in artifact paths and docker image tags imposes some limitations on the format we validate the format at the start of a build. Alternatively, we could sanitize `BUILDKITE_TAG` or refuse to upload artifacts when the value is not valid. Failing seems to be the most straightforward option.

Identify artifacts by BUILDKITE_TAG

---

ci/.debian/postinst
ci/.debian/prerm
ci/Cargo.toml
ci/scripts/buildkite-hook-wrapper

Instead of using _one_ wrapper script that delegates to the rust hooks and install it through symlinks we create a wrapper script for each hook on the fly.
The previous approach did not work because the buildkite agent _copied_ the hook to a temporary location with an opaque filename. Hence it was not possible to determine the hook by inspecting `$0`.

Don't use uniform hook wrapper script

---

registry/devnet/main.tf
registry/ffnet/main.tf
registry/ffnet/miners.tf
registry/ffnet/rpc-api.tf
registry/ffnet/validators.tf

This PR upgrades the node images tags. Neither on devnet nor on ffnet it should require a hard chain reset.
I'm not sure what to do next, will k8s notice that the files have changed and switch to the newer binary or do I have to do something manually? I couldn't find any documentation for that, maybe I should add it in this PR too.

Upgrade node to the newest master

---

registry/ffnet/validators.tf

Fixes #107.
Also remove `subdomain` cruft from previous experiments.

ffnet validators use persistent chain data

---

registry/devnet/main.tf
registry/devnet/miners.tf
registry/ffnet/miners.tf

At the moment the Kubernetes scheduler puts _all_ mining on one node in the mining pool. If this node is pre-empted all miners go down and it takes some time for them to start up and re-sync. This results in significant drops in the block rate which in turn triggers alerts.
By declaring [anti-affinity][1] for the mining pods we force the Kubernetes scheduler to distribute the mining pods evenly between the mining nodes. This means that if one node is pre-empted not all miners
go down.
[1]: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/

Distribute mining pods between all mining nodes

---

registry/ffnet/grafana_alerts.md
registry/ffnet/grafana_alerts_dashboard.json

We adjust the queries for the block import rate so that we don’t receive alerts when validator pods are updated.
When the Kubernetes statefulset for the validators is updated the new pods have labels that differ from the old pods. This results in two timeseries for, say, the `validator-0` instance. With the previous query for block import rate the rate of the timeseries for the old pod would steadily decline after the pod was deleted and the rate for the new pod would start at zero and steadily rise (see figure below). By summing the old and new pod for a given instance we can counteract this and get the correct value.
We also remove redundant checks for uptime and syncing.

Aggregate block import rate for alerting

---

ci/Cargo.toml
ci/etc/buildkite-hooks/buildkite-agent.cfg
ci/etc/systemd/system/buildkite-agent@.service.d/local.conf

The buildkite-agent systemd service now uses the config file that we provide. We also make the file a debian conffile so that it is not overwritten on package updates.

Use proper configuration for systemd unit

---

ci/Cargo.toml
ci/src/container/docker.rs

* Mount tmpfs with 'exec' option. This makes it possible to make files in /tmp executable. It is required to run Rust doc tests.
* Add `jq` as dependency

jq dependency and tmpfs exec

---

registry/README.md
registry/ffnet/main.tf
registry/main.tf

Since development on the registry is frozen we tear down the devnet for
the moment.

Tear down devnet

---

ci/src/bin/buildkite-command-hook.rs
ci/src/bin/buildkite-pre-checkout-hook.rs

* Decrypt secrets after checkout
* Specify sops config explicitly. Otherwise `sops` fails.

Fix pipeline secret decryption

---

ci/provision/cloud-init.yaml
ci/usr/bin/buildkite-hooks-setup

* Use Ubuntu 20.04 repo for kata containers build and specify keyserver
* Restart docker when linking in configuration at setup

Kata maintenance

---

ci/Cargo.toml
ci/etc/buildkite-hooks/hooks/environment
ci/src/bin/buildkite-print-environment.rs
ci/src/config.rs

We set the upload destination according the shell-based implementation.
The `BUILDKITE_ARTIFACT_UPLOAD_DESTINATION` environment variable can only be configured by buildkite’s script-based environment export. This is why we introduce the `buildkite-print-environment` command that is called by the `hooks/environment` script.

Set upload destination

---

ci/README.md
ci/macos/usr/local/etc/buildkite-agent/hooks/environment

This adds instructions on how to set up GCP tagged build uploads and Apple notarization on a macOS build host.
Closes https://github.com/radicle-dev/radicle-upstream/issues/1530.
Here's a build after the configuration and setup had been applied:
https://buildkite.com/monadic/radicle-upstream/builds/8581#c39e7bdd-0260-4fdc-bce2-8b45c4fb5c99
And the build artefact was uploaded for a test branch:
https://storage.googleapis.com/builds.radicle.xyz/radicle-upstream/c39e7bdd-0260-4fdc-bce2-8b45c4fb5c99/dist/radicle-upstream-0.2.1.dmg

Update macOS build host setup instructions

---

ci/macos/usr/local/etc/buildkite-agent/hooks/environment

The MacOS build agent now is allowed to build branches that start with `release-candidate/`.
We also tighten permissions around pull requests. The code seemed to suggest that pull request were rejected by the `BUILDKITE_REPO` check. This is however not the case. For pull requests to the `radicle-upstream` repo the `BUILDKITE_REPO` variable is also set to the allowed value. Before, pull requests were rejected because `BUILDKITE_BRANCH` looks like `<repo>:<branch>`. We now make this more explicit.

ci: mac agent builds release-candidate/ branches
